---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint code
        run: pnpm lint:code:ci --reporter=github

  commit-check:
    name: Lint commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint commit
        run: pnpm lint:commit

  unused-check:
    name: Lint unused
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint unused
        run: pnpm lint:unused

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Type check
        run: pnpm typecheck
      - name: Run tests
        run: pnpm test:coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Check package.json
        run: pnpm check:publint
      - name: Check types resolution
        run: pnpm check:attw
      - name: Check bundle size
        run: pnpm check:size

  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Dependency review
        uses: actions/dependency-review-action@v4
